### ISSUE TITLE
link preload requires as

### ISSUE THREAD

**Issue by jakeswenson** [darkobits/vite-plugin-webfonts#1]
Font preloading has been added, but it's not emitting proper preload links since `as="font"` is missing:

<img width="352" alt="image" src="https://user-images.githubusercontent.com/1854799/158073595-6d32ea80-f2b3-47a8-bc37-79d349c23e5e.png">

https://github.com/darkobits/vite-plugin-webfonts/blob/master/src/index.ts#L187

MDN Documentation on Preloading: https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/preload#the_basics

**Comment by darkobits** [comment]
Thanks for reporting this. I should be able to get it fixed in the next day or so. 🙂

**Comment by darkobits** [comment]
This should be fixed in b2d391d663c37769ef05acfab9a292629cefd717 and available in `v0.2.2`.

Going to close this, but please feel free to re-open it if the issue persists.
